FROM alpine

ENV PATH="$PATH:/app"
ENV TRACETEST_API_KEY ""

WORKDIR /app

COPY ./qualityTrace /app/qualityTrace
COPY ./agent/entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]

