/*
 * TraceTest
 *
 * OpenAPI definition for TraceTest endpoint and resources
 *
 * API version: 0.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type HealthzGet200Response struct {
	Status string `json:"status,omitempty"`
}

// AssertHealthzGet200ResponseRequired checks if the required fields are not zero-ed
func AssertHealthzGet200ResponseRequired(obj HealthzGet200Response) error {
	return nil
}

// AssertRecurseHealthzGet200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of HealthzGet200Response (e.g. [][]HealthzGet200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseHealthzGet200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aHealthzGet200Response, ok := obj.(HealthzGet200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertHealthzGet200ResponseRequired(aHealthzGet200Response)
	})
}
