apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "qualitytrace.fullname" . }}-analyzer
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: analyzer
        image: ghcr.io/kube-tarian/helmrepo-supporting-tools/curl:latest  
        command: ["/bin/sh", "-c"]
        args: 
        - >
          sleep 100 &&
          curl --location --request PUT 'http://{{ include "qualitytrace.fullname" . }}:11633/api/analyzers/current' \
            --header 'Content-Type: application/json' \
            --data '{
                "type": "Analyzer",
                "typePlural": "Analyzers",
                "spec": {
                    "id": "current",
                    "name": "analyzer",
                    "minimumScore": 0,
                    "enabled": {{ .Values.analyzer.enabled }},
                    "plugins": [
                        {
                            "name": "OTel Semantic Conventions",
                            "id": "standards",
                            "enabled": true,
                            "description": "Enforce trace standards following OTel Semantic Conventions",
                            "rules": [
                                {
                                    "id": "span-naming",
                                    "weight": 25,
                                    "errorLevel": "error",
                                    "name": "Span Naming",
                                    "description": "Enforce span names that identify a class of Spans",
                                    "errorDescription": "",
                                    "tips": []
                                },
                                {
                                    "id": "required-attributes",
                                    "weight": 25,
                                    "errorLevel": "error",
                                    "name": "Required Attributes",
                                    "description": "Enforce required attributes by span type",
                                    "errorDescription": "This span is missing the following required attributes:",
                                    "tips": [
                                        "This rule checks if all required attributes are present in spans of given type"
                                    ]
                                },
                                {
                                    "id": "attribute-naming",
                                    "weight": 25,
                                    "errorLevel": "error",
                                    "name": "Attribute Naming",
                                    "description": "Enforce attribute keys to follow common specifications",
                                    "errorDescription": "The following attributes do not follow the naming convention:",
                                    "tips": [
                                        "You should always add namespaces to your span names to ensure they will not be overwritten",
                                        "Use snake_case to separate multi-words. Ex: http.status_code instead of http.statusCode"
                                    ]
                                },
                                {
                                    "id": "no-empty-attributes",
                                    "weight": 25,
                                    "errorLevel": "error",
                                    "name": "No Empty Attributes",
                                    "description": "Disallow empty attribute values",
                                    "errorDescription": "The following attributes are empty:",
                                    "tips": [
                                        "Empty attributes don'\''t provide any information about the operation and should be removed"
                                    ]
                                }
                            ]
                        },
                        {
                            "name": "Common Problems",
                            "id": "common",
                            "enabled": true,
                            "description": "Help you find common mistakes with your application",
                            "rules": [
                                {
                                    "id": "prefer-dns",
                                    "weight": 100,
                                    "errorLevel": "error",
                                    "name": "Prefer DNS",
                                    "description": "Enforce usage of DNS instead of IP addresses",
                                    "errorDescription": "The following attributes are using IP addresses instead of DNS:",
                                    "tips": []
                                }
                            ]
                        },
                        {
                            "name": "Security",
                            "id": "security",
                            "enabled": true,
                            "description": "Help you find security problems with your application",
                            "rules": [
                                {
                                    "id": "secure-https-protocol",
                                    "weight": 30,
                                    "errorLevel": "error",
                                    "name": "Secure HTTPS Protocol",
                                    "description": "Enforce usage of secure protocol for HTTP server spans",
                                    "errorDescription": "The following attributes are using insecure http protocol:",
                                    "tips": []
                                },
                                {
                                    "id": "no-api-key-leak",
                                    "weight": 70,
                                    "errorLevel": "error",
                                    "name": "No API Key Leak",
                                    "description": "Disallow leaked API keys for HTTP spans",
                                    "errorDescription": "The following attributes are exposing API keys:",
                                    "tips": []
                                }
                            ]
                        }
                    ]
                }
            }'
      restartPolicy: Never
  backoffLimit: 1



