{{- if not .Values.postgresql.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: create-user-database
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: create-user-database
    spec:
      containers:
      - name: postgresql-client
        image: {{ .Values.postgresql.image.registry }}/{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}
        command:
          - "/bin/bash"
          - "-c"
          - |
            psql -h {{ .Values.externalPostgresql.host }} -p 5432 -U postgres -v db_password=$DB_PASSWORD -f /script/create-database.sql
        env:
          - name: PGPASSWORD
            {{- if not .Values.externalPostgresql.existingSecret }}
            value: "{{ .Values.externalPostgresql.postgresqlPassword }}"
            {{- else }}
            valueFrom:
              secretKeyRef:
                name: {{ .Values.externalPostgresql.existingSecret.name }}
                key: {{ .Values.externalPostgresql.existingSecret.passwordKey }}
            {{- end }}
          - name: DB_PASSWORD
            {{- if not .Values.externalPostgresql.qualitytrace.existingSecret }}
            value: "{{ .Values.externalPostgresql.qualitytrace.password }}"
            {{- else }}
            valueFrom:
              secretKeyRef:
                name: {{ .Values.externalPostgresql.qualitytrace.existingSecret.name }}
                key: {{ .Values.externalPostgresql.qualitytrace.existingSecret.passwordKey }}
            {{- end }}
        volumeMounts:
          - name: script-volume
            mountPath: /script
            readOnly: true
      restartPolicy: Never
      volumes:
        - name: script-volume
          configMap:
            name: postgresql-query
{{- end }}

