apiVersion: v1
kind: Service
metadata:
  name: {{ include "qualitytrace.fullname" . }}
  labels:
    {{- include "qualitytrace.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.server.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.server.otlpGrpcPort }}
      targetPort: otlp-grpc
      protocol: TCP
      name: otlp-grpc
    - port: {{ .Values.server.otlpHttpPort }}
      targetPort: otlp-http
      protocol: TCP
      name: otlp-http
  selector:
    {{- include "qualitytrace.selectorLabels" . | nindent 4 }}
